server:
  port: 7201

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: hello-service-consumer
logging:
  config: classpath:logback.xml
# 开启hystrix
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  # 解压缩
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true