server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  config: classpath:logback.xml
zuul:
  routes:
    film-service:
     path: /film-api/**
    cinema-servie:
      path: /cinema-api/**
